version: "1.0"

services:
  web: 
    build: ./
    command: python /myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - 8000:8000

    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data:
